name: ClearLagg
main: ClearLagg\Loader
version: 1.0.0
api: 1.0.0
author: LegendOfMCPE
website: https://github.com/LegendOfMCPE/ClearLagg
description: Port of Bukkit ClearLagg for PocketMine Servers
permissions:
    clearlagg:
        default: false
        description: "Allows access to all ClearLagg features."
        children:
            clearlagg.*:
                default: false
                description: "Allows access to all ClearLagg features."
            clearlagg.command:
                default: false
                description: "Allows access to all ClearLagg commands."
                children:
                    clearlagg.command.*:
                        default: false
                        description: "Allows access to all ClearLagg commands."
                    clearlagg.command.clearlagg:
                        default: op
                        description: "Allows access to the clearlagg command."
                        # children:
                        # I will add subcommand permissions later. -Luke
