name: ClearLagg
main: ClearLagg\Loader
version: 1.0.0
api: [1.0.0]
website: https://github.com/LegendOfMCPE/ClearLagg
permissions:
    clearlagg:
        default: op
        description: "Access any ClearLagg features"
        children:
            clearlagg.command:
                default: op
                description: "Access to the command feature"
                children: []
